
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIV ID IF LBRACE MINUS NUMBER PLUS RBRACE SEMI TIMES WITHwaeStart : wae SEMIwae : NUMBERwae : IDwae : LBRACE PLUS wae wae RBRACEwae : LBRACE MINUS wae wae RBRACEwae : LBRACE TIMES wae wae RBRACEwae : LBRACE DIV wae wae RBRACEwae : LBRACE IF wae wae wae RBRACEwae : LBRACE WITH LBRACE alist RBRACE wae RBRACEalist : LBRACE ID wae RBRACEalist : LBRACE ID wae RBRACE alist'
    
_lr_action_items = {'NUMBER':([0,3,4,7,8,9,10,11,13,14,15,16,17,23,26,27,28,29,31,32,33,37,],[3,-2,-3,3,3,3,3,3,3,3,3,3,3,3,-4,-5,-6,-7,3,3,-8,-9,]),'ID':([0,3,4,7,8,9,10,11,13,14,15,16,17,23,24,26,27,28,29,31,32,33,37,],[4,-2,-3,4,4,4,4,4,4,4,4,4,4,4,31,-4,-5,-6,-7,4,4,-8,-9,]),'LBRACE':([0,3,4,7,8,9,10,11,12,13,14,15,16,17,18,23,26,27,28,29,31,32,33,36,37,],[5,-2,-3,5,5,5,5,5,18,5,5,5,5,5,24,5,-4,-5,-6,-7,5,5,-8,24,-9,]),'$end':([1,6,],[0,-1,]),'SEMI':([2,3,4,26,27,28,29,33,37,],[6,-2,-3,-4,-5,-6,-7,-8,-9,]),'RBRACE':([3,4,19,20,21,22,25,26,27,28,29,30,33,34,35,36,37,38,],[-2,-3,26,27,28,29,32,-4,-5,-6,-7,33,-8,36,37,-10,-9,-11,]),'PLUS':([5,],[7,]),'MINUS':([5,],[8,]),'TIMES':([5,],[9,]),'DIV':([5,],[10,]),'IF':([5,],[11,]),'WITH':([5,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'waeStart':([0,],[1,]),'wae':([0,7,8,9,10,11,13,14,15,16,17,23,31,32,],[2,13,14,15,16,17,19,20,21,22,23,30,34,35,]),'alist':([18,36,],[25,38,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> waeStart","S'",1,None,None,None),
  ('waeStart -> wae SEMI','waeStart',2,'p_waeStart','WAEParser.py',6),
  ('wae -> NUMBER','wae',1,'p_wae_1','WAEParser.py',10),
  ('wae -> ID','wae',1,'p_wae_2','WAEParser.py',14),
  ('wae -> LBRACE PLUS wae wae RBRACE','wae',5,'p_wae_3','WAEParser.py',18),
  ('wae -> LBRACE MINUS wae wae RBRACE','wae',5,'p_wae_4','WAEParser.py',22),
  ('wae -> LBRACE TIMES wae wae RBRACE','wae',5,'p_wae_5','WAEParser.py',26),
  ('wae -> LBRACE DIV wae wae RBRACE','wae',5,'p_wae_6','WAEParser.py',30),
  ('wae -> LBRACE IF wae wae wae RBRACE','wae',6,'p_wae_7','WAEParser.py',34),
  ('wae -> LBRACE WITH LBRACE alist RBRACE wae RBRACE','wae',7,'p_wae_8','WAEParser.py',38),
  ('alist -> LBRACE ID wae RBRACE','alist',4,'p_alist_1','WAEParser.py',42),
  ('alist -> LBRACE ID wae RBRACE alist','alist',5,'p_alist_2','WAEParser.py',46),
]
