jupyter nbconvert --to html .\01-intro.ipynb
jupyter nbconvert --to html .\02-strings.ipynb
jupyter nbconvert --to html .\03-lists-tuples-dictionaries-sets.ipynb
jupyter nbconvert --to html .\04-conditionals.ipynb
jupyter nbconvert --to html .\05-loops.ipynb
jupyter nbconvert --to html .\06-comprehensions.ipynb
jupyter nbconvert --to html .\07-exceptions.ipynb
jupyter nbconvert --to html .\08-files.ipynb
jupyter nbconvert --to html .\09-functions.ipynb
jupyter nbconvert --to html .\10-lambdas.ipynb
jupyter nbconvert --to html .\11-classes.ipynb
jupyter nbconvert --to html .\12-logging.ipynb
jupyter nbconvert --to html .\13-testing.ipynb